### ISSUE TITLE
2014 supported ?

### ISSUE THREAD

**Issue by pmcgrath** [denisenkom/go-mssqldb#125]
Does the driver support sql express 14 ?
I am using go v1.5 running on Windows 7 64 bit for this test

I have tested with a server 2012 instance successfully using the following from the examples directory

```
  go run .\tsql.go -S 'pluto' -d master
  > select @@version

  Microsoft SQL Server 2012 (SP1) - 11.0.3373.0 (X64)
          Jun 29 2013 21:15:12
          Copyright (c) Microsoft Corporation
          Developer Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

but when I try to test against a local 2014 express instance

```
  go run .\tsql.go -S 'pmcgrath\sqlexpress' -d master
```

it just sits there and does nothing not even exiting, so seems to ignore the timeouts also, any ideas ?

Thanks in advance
Pat

**Comment by mikewilliamson** [comment]
Hi Pat,

I can confirm that I've successfully used this driver to connect to SQL Server Express 14.  I'm afraid I can't offer any insight into your problem, but it will definitely work if everything is configured properly.

Good luck,

-Mike

**Comment by ArtnerC** [comment]
I too have had this issue connecting to a local SQL Express instance. I have since moved to just connecting to our SQL Server instance (which has its own [issues](https://github.com/denisenkom/go-mssqldb/issues/105)). However, the [odbc package](https://github.com/alexbrainman/odbc) did work, though with weirder handling of some data types I can't specifically remember the nature of. Hope this can get fixed, would prefer to use the specific driver over the generalized one.

**Comment by mavlyutov** [comment]
any update of this one?
have the same issue

**Comment by fdgit** [comment]
That happens if the SQLBrowser service is not running.   It should really fail with some sort of "instance not found error" type of error.
(Possibly unrelated, but sql express sometimes has tcp disabled by default.  Check it in config manager)

**Comment by ozkar99** [comment]
> That happens if the SQLBrowser service is not running. It should really fail with some sort of "instance not found error" type of error.

+1 for this, have same issue, SQLBRowser service was NOT running.

**Comment by denisenkom** [comment]
Added timeout to getInstances operation.  It should fix this issue.  Thanks everyone!
