### ISSUE TITLE
How to read data from the result set using stored procedure

### ISSUE THREAD

**Issue by samrat-roy** [denisenkom/go-mssqldb#152]
Hi,
I am new to this golang. My requirement is to call SQL server and get data from the DB using stored procedure. I am using the below code. I am getting the result back but when i am trying to access the data its showing empty. Same code is working when i am doing in-line query .Please let me know where i am making mistake.

// Calling SP here by passing input parameter
row, err := db.Query("exec [GetEmployeeDetails] ?",1)
      if err != nil {
        fmt.Println(err)
    } else {
        for row.Next() {
        var firstname string
              row.Scan(&firstname)
        fmt.Println(firstname)  
        }

**Comment by denisenkom** [comment]
try changing query to:
set nocount on; exec [GetEmployeeDetails] ?

**Comment by leonardogazio** [comment]
@denisenkom Thank you SO MUCH bro!!!!!!!! I spent 3 days fighting against Google trying to resolve that! Nothing worked, my stored procedure executed but no result, executing "set nocount on;"before my procedure did the trick! I really thought that was a bug on GO database/sql library just because I use that stored procedure in other projects with other languages such as Java/PHP/Pascal, but with those other languages I don't need to set nocount on.

Thank you once again.
