### ISSUE TITLE
Add support for connection retry logic equivalent to MultisubnetFailover 

### ISSUE THREAD

**Issue by LukeMauldin** [denisenkom/go-mssqldb#191]
In .NET 4.6.1, SqlClient is intelligent enough to automatically detect if the SQL connection is to a  AlwaysOn Availability Group or a SQL Cluster and sets MultisubnetFailover which optimizes client failover behavior.  See https://blogs.msdn.microsoft.com/dotnet/2015/11/30/net-framework-4-6-1-is-now-available/  and https://msdn.microsoft.com/en-us/library/hh205662(v=vs.110).aspx  

Even if the Golang equivalent doesn't support MultisubnetFailover auto detection, it would be nice to offer an similar connection string option that can be manually set.

**Comment by mikewilliamson** [comment]
If I correctly understand what MS are saying in their blog, this may have already been implemented by PR #124 last year.  My understanding of MultiSubnetFailover=true is that it will make the .NET driver dial the various members of the cluster in parallel, so you don't have to wait for one to timeout before trying the next one.   Since #124, the Go driver will always do this when connecting to an Availability Group.

**Comment by LukeMauldin** [comment]
Will the Go driver also do this when connecting to a SQL Cluster instance?

**Comment by mikewilliamson** [comment]
I'm not sure how SQL Clusters are implemented.  The specific behaviour of the driver which implements AG connections is:

1. Resolve DNS host name into a list of IP addresses
2. Dial them all in parallel
3. Proceed with the first one that accepts a connection
4. Error if they all timeout

If a SQL Cluster connection is presented to clients in the same way as an AG connection, then it should work fine.  The code doesn't really know that it's connecting to an AG per se, it only knows that the DNS resolution returns a list rather than a single IP address.

**Comment by LukeMauldin** [comment]
Thank you for the update.  I have tested the Go driver against a SQL 2016 availability group and compared the results against a C# application using .NET 4.6.2.  In the majority of cases, the C# application transitions seamlessly when the availability group fails over.  However, the Go driver always reports an error: `xxx:1433': dial tcp 138.254.135.78:1433: i/o timeout`
I have made the Go and C# test applications to have the same logic.  I am including a link to the Go application: (https://play.golang.org/p/f2VVOjDQ3N)  I have tried various settings for the "dial timeout" field but there is always an error reported.  Could the behavior of the Go driver be updated to match the C# one?  If needed, I can try to post the C# code as well.

**Comment by mikewilliamson** [comment]
I can't quite see how this would work given the architecture of the Go sql package.  The problem is that AG failover isn't _really_ seamless.  You have an open TCP connection to one server in the cluster, and if that server dies, you have to establish a new connection to another server, authenticate again, etc.  If you were in the middle of a transaction, you have to start over again from the beginning.  

I think the go sql package will sometimes transparently retry a single statement if a connection throws an error (so for example, if you got a connection from the pool that had timed out, you don't have to deal with that).  But it couldn't possibly be expected to save and replay an arbitrary number of SQL statements within a transaction.  So in the most general case, it's inevitable that an error will be passed up to the application, which will have to catch it and decide what to do.  

I have no idea what kind of magic the .NET driver might be doing to make it appear more seamless.  I'm not familiar with that technology at all, but I suppose the relationship between the driver and the programming language are quite different.  For a single statement, it could be trapping the error, establishing a new connection, and retrying it for you.  But this is actually a dangerous thing to do -- depending on the failure mode this could lead to the statement being executed twice.

Anyway, all the stuff that we've written in Go deals well enough with AG failover by handling the error in one way or another.

**Comment by kardianos** [comment]
I think it would be possible; you would need to create a package private mapping per DSN that then would write down the current state of the remotes: remote 1 appears down , remote 2 looking good, use that first.

**Comment by mikewilliamson** [comment]
I don't think caching the last-known-good server and trying it first would be any better than the current approach of always trying all servers in the cluster in parallel.  It would definitely be worse when a failover occurs.

In any case, this wouldn't address the central problem raised by @LukeMauldin   When the primary server in an AG cluster fails, a new primary is elected.  All clients have to find the new primary and establish a new connection.  I believe it to be impossible to hide that failover process from the client without the risk of statements (e.g. inserts) being executed twice.

**Comment by LukeMauldin** [comment]
Thank you for all of your responses. After much consideration, I agree that the retry logic should be contained entirely in the application.
