### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by zzwind** [denisenkom/go-mssqldb#235]
my environment is win10 ,and my sqlserver on a remote server,
when i run the example with the right user,password,port.
but cann't connect success.
i'm using windows auth,and i connected two sqlserver instance are all faild.
is this a bug? or my person problem?

**Comment by khannz** [comment]
I'm joining this issue since it recently become mine too.

- Code executes locally on dev box with win10.
- `SQL Server 11.0.5058` instance is remote
- `User id`, `password`, `port` and even `ServerSPN` are correct

**Addition:** local login works great, with Windows Auth problem is same as @zzwind reported:

```
wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by kardianos** [comment]
From your last error message it looks like your certificate name is different then the DNS name you use to connect to the server. If that is the case, you need to set "hostNameInCertificate" in the connection string to match the certificate name.

**Comment by Gelyea** [comment]
this issue is meetting me too,  any help?
--
wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by davegiffin** [comment]
server=192.168.1.134;user id=sa;password=xxxx;database=master;encrypt=disable
