### ISSUE TITLE
does deadline interfere with multiple active queries

### ISSUE THREAD

**Issue by rbucker** [denisenkom/go-mssqldb#270]
I know that MS has a specific definition for MARS. My scenario is that I have nested open queries....

select * from table....
   read a row
   select * from table
   process the results
loop

If the inner SQL takes too long will the deadline (hardcoded to 5 seconds) terminate or cause a reset connection.

**Comment by kardianos** [comment]
@rbucker Neither this driver nor Azure supports MARS. Both however both this driver and Azure support returning multiple result sets.

From the get go I would look into cursor or cross apply.

But your issue is with query timeout. Have you tried to set either of the DSN parameters:
```
"connection timeout" - in seconds (default is 30)
"dial timeout" - in seconds (default is 5)
```
I'm assuming the only one that would be of importance to you is the connection timeout.

**Comment by rbucker** [comment]
yep, tried the timeouts with all sorts of different values.

**Comment by kardianos** [comment]
Could I reproduce it with `select 1;sleep 40000; select 1;` ?
