### ISSUE TITLE
Return ResultNoRows from Exec

### ISSUE THREAD

**Issue by j0hnwhyte** [denisenkom/go-mssqldb#479]
I see in mssql.go that the `exec()` function returns nil as the `Result`. Apparently the correct response would be `driver.ResultNoRows` if it's unimplemented. Could you please check this out?

**Comment by v-kaywon** [comment]
Yes you're right. I will start looking into it.

**Comment by v-kaywon** [comment]
I started looking into it. The driver only returns nil when there is an error executing the command. Otherwise, if the execution is successful, a Result is returned even if it was a DDL command.

I was looking into other drivers listed in https://github.com/golang/go/wiki/SQLDrivers as well, seems like most drivers do not have `driver.ResultNoRows` implemented, and I think there is a reason for that, and that is it is difficult to detect whether or not a command is a DDL command.

What test case are you using that requires `driver.ResultNoRows`? Does the currently implementation of `Result` (returning LastInsertId -1 and RowsAffected 0) satisfy your need?

**Comment by j0hnwhyte** [comment]
Line 627, I see no way it could return a `Result`:

```go
func (s *Stmt) exec(ctx context.Context, args []namedValue) (res driver.Result, err error) {
	if !s.c.connectionGood {
		return nil, driver.ErrBadConn
	}
	if err = s.sendQuery(args); err != nil {
		return nil, s.c.checkBadConn(err)
	}
	if res, err = s.processExec(ctx); err != nil {
		return nil, s.c.checkBadConn(err)
	}
	return
}
```

**Comment by j0hnwhyte** [comment]
Sorry, I didn't see that the `res` is assigned in the last call. It's strange though that it gave me nil, maybe I overlooked something. I'll do some more research. Thanks (close this in a few days if you hear nothing from me)
