### ISSUE TITLE
MSSQL connection started failing on 2/6/20

### ISSUE THREAD

**Issue by arjitj2** [denisenkom/go-mssqldb#554]
**Describe the bug**

In production, our ETLs started failing yesterday with "Login error: mssql: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication."

One of the master commits yesterday, either `bbfc9a55622eeb8e47808e0f7270efcf5ae3dce2` or `3f988484a57ee992b0febb2257ca939c58abfd2a` started causing this issue.

**Reproduce**
We're just doing a simple `sql.Open()` using this driver and a connection string formatted like `"server=%s;user id=%s;password=%s;port=%s"`

**Fix for now**
I am manually checking out your last "known" working commit `0f454e2ecd6ad8fb4691cdbf10e399e05ca03784` in our docker container to run our ETLs.

**Comment by kardianos** [comment]
Thank you for reporting this. We'll look into it right away.

**Comment by kardianos** [comment]
@arjitj2 Can I get a few details from you?
 1. What OS is your client and server on?
 2. What version of Go?
 3. Do you use Windows Authentication or SQL Server authentication?

**Comment by arjitj2** [comment]
1) Client is a docker container built on top of the `golang:1.12.0-alpine3.9` docker image.
Server details:
SQL_Version    Edition
SQL Server 2016    Enterprise Edition (64-bit)

2) Go version: 1.12.0

3) Windows authentication

**Comment by kardianos** [comment]
Okay, I think I'm getting a picture for what happened.  Thanks again for creating the issue and using CI/CD.

Piror to https://github.com/denisenkom/go-mssqldb/commit/3f988484a57ee992b0febb2257ca939c58abfd2a the driver only supported NTLM(v1). At that commit NTLMv2 is negotiated now. However, NTLMv2 may enforce stricter security and system requirements. Does the "User ID" have a domain part currently?  If not, maybe that can be set?

@sboutzen Can we force use of NTLM rather then NTLMv2?

**Comment by arjitj2** [comment]
by domain part, i think you mean it's formatted like `domain\user_name` ? If so, yes, we are passing the username like that

**Comment by sboutzen** [comment]
We could force use of NTLM by ignoring the `Negotiate NTLM2 Key` flag and negotiating the old NTLM way. However, since the server is sending the `Negotiate NTLM2 Key` flag, it should be able to negotiate using NTLMv2.

@arjitj2 Could you print the bytes [from here](https://github.com/denisenkom/go-mssqldb/blob/master/ntlm.go#L392) and pass them along to me, or if you're comfortable, tell me which flags are set? If you send the bytes, check the string representation of it beforehand, and obfuscate your domain if you wish. It is the type 2 message in the NTLM authentication. This will allow me to dig into the protocol and find out what your domain is expecting which my implementation doesn't do.

**Comment by sboutzen** [comment]
Also, is your client and server on the same machine / container?

**Comment by sboutzen** [comment]
I just had a look at what my corporate domain sends back as flags, and it seems to me there are two possibilities of what is wrong:

1. The server can set a flag suggesting it supports and auth method, which it does not actually support. In my domain, the server is setting the `Negotiate NTLM` flag, however before implementation v2, i got the error you got. So either the previous implementation of NTLMv1 was missing something, or my server is a lier! This would mean that your server could be sending the NTLMv2 flag, without actually supporting it.

2. Something in my implementation of NTLMv2 is missing.

**Comment by AnilkumarGajula** [comment]
We are also getting same issue after go.mod is updated with github.com/denisenkom/go-mssqldb v0.0.0-20200206145107-3f988484a57e. If we revert go.mod with github.com/denisenkom/go-mssqldb v0.0.0-20200131184339-0f454e2ecd6a everything works fine.

Environment where issue is observed:
Client is a docker container built on top of the golang:1.13.0-alpine3.9 docker image.
Server details: SQL_Version Edition
                       SQL Server 2016 Enterprise Edition (64-bit)
Go version: 1.13.5
OS: Linux
Windows authentication "domain\username" .
Our SQL server supports only Kerberos authentication.
Note: Issue is seen only when it is run on Linux OS. It wont be seen when we run it on Windows machine.

@arjitj2 : Could you please share any work around for this issue if you are using? 
@sboutzen : Were you able to figure out the root-cause of this issue?

**Comment by sboutzen** [comment]
@AnilkumarGajula I never received a response from @arjitj2, so i havent looked into it since then. If you could set a breakpoint [here](https://github.com/denisenkom/go-mssqldb/blob/master/ntlm.go#L392), print the `bytes` variable and give me that (on the failing OS), i would be able to dig into it.

**Comment by AnilkumarGajula** [comment]
@sboutzen Here is the string representation as you requested.

NTLMSSP      8   ��W��y���        � � H
 98   C O M P A N Y   C O M P A N Y   P R F - dbname - S Q L 000   C O M P A N Y . C O R P  8 P R F - dbname - S Q L 0 1 1 . C O M P A N Y . C O R P   C O M P A N Y . C O R P  /�}���

**Comment by sboutzen** [comment]
I apologize @AnilkumarGajula , i should have been more precise.

What i need are the bytes, not a string representation of the bytes. Scrambling the bytes that include company name is fine.

**Comment by AnilkumarGajula** [comment]
You could easily convert above string into bytes. 
if you still need bytes from program itself let me know..

**Comment by sboutzen** [comment]
Maybe you could elaborate on how to do that? Im not sure how i would do that, the � translate to lost information afaik, and multiple important bits would be set in each of them.

I still need the bytes unless im missing some obvious way to convert your message to the actual bytes.

**Comment by AnilkumarGajula** [comment]
[78 84 76 77 83 83 80 2 16 16 56 5 239 191 189 239 191 189 2 239 191 189 101 239 191 189 239 191 189 1 239 191 189 66 239 191 189 239 191 189 72 32 57 56 15 67 79 77 80 65 78 89 2 16 67 79 77 80 65 78 89 1 28 80 82 70 45 68 66 45 83 81 76 48 49 49 4 26 67 79 77 80 65 78 89 46 67 79 82 80 3 56 80 82 70 45 68 66 45 83 81 76 48 49 49 46 67 79 77 80 65 78 89 46 67 79 82 80 5 26 67 79 77 80 65 78 89 46 67 79 82 80 7 8 239 191 189 239 191 189 239 191 189 239 191 189 9 239 191 189 239 191 189 1]

to convert bytes to string i use string(bytes).
to convert string to bytes i use []byte(string).

**Comment by sboutzen** [comment]
Thank you, i will investigate

**Comment by sboutzen** [comment]
Did you strip some 0 bytes? That message has an invalid signature

**Comment by AnilkumarGajula** [comment]
No. I have replaced company name and DB name.

**Comment by sboutzen** [comment]
Are you just doing `fmt.Println(bytes)` ?

**Comment by AnilkumarGajula** [comment]
Yes.
 fmt.Println("bytes are ****************",bytes)

**Comment by sboutzen** [comment]
Something is wrong with that message, and if that was really the message you were getting, it would not have worked before either. The correct first 8 bytes are `78, 84, 76, 77, 83, 83, 80, 0`

Do you by any chance have a terminal which manipulates `stdout` in some way?

If you dont mind, i would like you to try this: `fmt.Fprintln(os.Stderr, bytes)`

Also, could you stop in the debugger and check that the byte array you are printing matches the byte array you can see in the debugger?

**Comment by AnilkumarGajula** [comment]
Using fmt.Fprintln(os.Stderr, bytes) its same bytes printed. 
What bytes you are expecting? What obesrvation you want to see in bytes. 
sending bytes without modification.
78 84 76 77 83 83 80 0 2 0 0 0 16 0 16 0 56 0 0 0 5 130 137 2 182 181 2 185 168 72 143 206 0 0 0 0 0 0 0 0 188 0 188 0 72 0 0 0 10 0 57 56 0 0 0 15 70 0 65 0 78 0 65 0 84 0 73 0 67 0 83 0 2 0 16 0 70 0 65 0 78 0 65 0 84 0 73 0 67 0 83 0 1 0 28 0 80 0 82 0 70 0 45 0 68 0 65 0 88 0 45 0 83 0 81 0 76 0 48 0 49 0 49 0 4 0 26 0 70 0 65 0 78 0 65 0 84 0 73 0 67 0 83 0 46 0 67 0 79 0 82 0 80 0 3 0 56 0 80 0 82 0 70 0 45 0 68 0 65 0 88 0 45 0 83 0 81 0 76 0 48 0 49 0 49 0 46 0 70 0 65 0 78 0 65 0 84 0 73 0 67 0 83 0 46 0 67 0 79 0 82 0 80 0 5 0 26 0 70 0 65 0 78 0 65 0 84 0 73 0 67 0 83 0 46 0 67 0 79 0 82 0 80 0 7 0 8 0 172 89 116 210 28 246 213 1 0 0 0 0

**Comment by sboutzen** [comment]
This is what i wanted, thanks.

I will now investigate

**Comment by sboutzen** [comment]
@AnilkumarGajula Looking at the payload you got, everything seems fine and dandy, so from that point of view i cannot see what would be wrong. I suspect this might be a configuration issue, so potentially you could configure your linux setup to handle NTLM2 authentication. I was unable to set up an sqlserver on a linux host in my own domain because of licensing issues, so i cannot say for sure. 

Are you using CNTLM on your linux machine?

@kardianos If i am correct, and this is a configuration issue, then there is no strictly necessary code change. However, this does break backwards compatibility as we have seen, which of course is bad.
I have two possible suggestions as to how we can handle this failed logon:

1. Enable the caller to force NTLM1 authentication, so once it fails, if the caller is on a Linux host, we can suggest that she can force NTLM1. This at least gives people a hint to a work around. Downside is that it does not unbreak backwards compatibility.

2. Do another logon using NTLM1 if the caller is on Linux and NTLM2 failed. This unbreaks backwards compatibility, but it seems dirty, and it can cause people to quicklier lock their domain users if they accidentedly write an incorrect password, due to the double login.

What do you think? Maybe you have some better suggestions?

**Comment by sboutzen** [comment]
@AnilkumarGajula One more thing, could you try and see if you are able to connect to the sqlserver on your linux host using the [other mssql driver](https://github.com/minus5/gofreetds)?

This one uses cgo to use a very large tds implementation (freetds), and if you are able to connect using that, it would make sense for me to dig into freetds and see what they are doing.

**Comment by AnilkumarGajula** [comment]
@sboutzen thanks for analysis. I will check my code with other mssql driver.
i will also check what authentication is set up in linux machine.

**Comment by AnilkumarGajula** [comment]
@sboutzen Linux box uses SSSD authentication.
SSSD does not support NTLM authentication.

**Comment by NikitaDef** [comment]
#570 I create the fix.
@arjitj2 @AnilkumarGajula @sboutzen please check with my fix

**Comment by NikitaDef** [comment]
@kardianos I check on a few servers, but only with same domain name

**Comment by kardianos** [comment]
Thanks @NikitaDef . I'll wait a few days to hear back from them. Otherwise the change looks good to me.

**Comment by arjitj2** [comment]
@NikitaDef my brief test showed it worked for me!

**Comment by arjitj2** [comment]
Worked like a charm, closing this ticket, thanks a bunch @NikitaDef

**Comment by AnilkumarGajula** [comment]
@NikitaDef Thanks for the fix.
I have verified with my code and it works.
