### ISSUE TITLE
Help needed with uniqueidentifier

### ISSUE THREAD

**Issue by scohen28** [denisenkom/go-mssqldb#56]
I'm retrieving the ID from a sql server database as follows:

import ("github.com/nu7hatch/gouuid")
var theID []byte
err := db.QueryRow("select id from table where item='xxx').Scan(&theID)
fmt.Println(theID)
idStr, _ := uuid.Parse(theID)
fmt.Println(idStr)

Prints:
  [249 214 3 106 70 136 42 75 185 33 204 184 168 141 203 14]
  f9d6036a-4688-2a4b-b921-ccb8a88dcb0e

When I directly query the table using Sql Management Studio, for the same query I get:
  6A03D6F9-8846-4B2A-B921-CCB8A88DCB0E

I also tried the following, but it returns the same 'f9d...' value
   b := theID
   b[6] = (b[6] & 0x0F) | 0x40
   b[8] = (b[8] &^ 0x40) | 0x80
   theIDStr := fmt.Sprintf("%x-%x-%x-%x-%x", b[:4], b[4:6], b[6:8], b[8:10]

What is the correct parsing function to use on the returned []byte to resolve to the same value that Sql Server is presenting?

**Comment by sachinwalia2k8** [comment]
Thanks @scohen28 this was really helpful.

**Comment by shueybubbles** [comment]
@kardianos  one problem with requiring an app to scan to *mssql.UniqueIdentifier instead of *interface{} is the scanner doesn't currently support a null uniqueidentifier.
`select convert(uniqueidentifier, null)` will fail
`sql: Scan error on column index 0, name "": mssql: cannot convert <nil> to UniqueIdentifier`
