### ISSUE TITLE
how to get the update result? 

### ISSUE THREAD

**Issue by hopestar** [denisenkom/go-mssqldb#668]
hello ~  could you tell me how to get the update result? 
the query like "update  table  set xx=1 WHERE id=7"
 i using rows.Next() , but it always return  false.
how to get the result like rows.RowsAffected ？
thanks.

**Comment by kardianos** [comment]
Learn T-SQL a bit better. Please review the docs for the `update` clause: https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15

What you want is:
```
update t set
   xx=1
output
  inserted.*
from
  table t
where
  t.id = 7
;
```

**Comment by tc-hib** [comment]
Hello,

I think what you are looking for is the [Exec](https://golang.org/pkg/database/sql/#DB.ExecContext) method.
Use it instead of `Query`.

Please be aware that `LastInsertId` cannot function properly with SQL Server.
You would need to use `Query` again, and an `OUTPUT` clause (might not work if you have triggers) or a second statement:
```sql
INSERT ...
;SELECT SCOPE_IDENTITY()
```

**Comment by hopestar** [comment]
> Learn T-SQL a bit better. Please review the docs for the `update` clause: https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15
> 
> What you want is:
> 
> ```
> update t set
>    xx=1
> output
>   inserted.*
> from
>   table t
> where
>   t.id = 7
> ;
> ```

yes, thank you very much ~

**Comment by dzsquared** [comment]
@hopestar - if you're all set here, can you make the issue closed?
