### ISSUE TITLE
What means connection parameter "keepAlive"?

### ISSUE THREAD

**Issue by haochun** [denisenkom/go-mssqldb#76]
does it means keepAlive the sql connection?but,the sql connection is TCP connection,Isn't it keepAlive?i want to communication with you,but i does not know how to contact you,so i put a new issue.

**Comment by tristanwietsma** [comment]
i believe the default for mssql is that after 30 seconds of idle, the connection is dropped. i've been running into this myself with a little REST interface; I've found that if i GET a json after that idle period, it'll hang. However, if i refresh the page, the query proceeds.

@denisenkom is that behavior by design? i ask because i'm planning to just have a ping before every query.

**Comment by tristanwietsma** [comment]
nevermind; found go-mssqldb#44

**Comment by haochun** [comment]
@tristanwietsma it means that if i does not use the connection some time,it will be closed?

**Comment by tristanwietsma** [comment]
@haochun http://blogs.msdn.com/b/sql_protocols/archive/2006/03/09/546852.aspx
