### ISSUE TITLE
Azure SQL connection is dropped after idle for ~2 minutes

### ISSUE THREAD

**Issue by jamesRaybould** [denisenkom/go-mssqldb#81]
When using an Azure MSSQL database if the connection is left idle for approximately 2 minutes will throw the error `WSARecv tcp 10.65.36.87:58150: i/o timeout`

I have a basic workaround that involves setting `SetMaxIdleConns(0)`, this solves the timeout issue but introduces a large level of latency into each database call as it appears to create a brand new connection every time.

**Comment by jamesRaybould** [comment]
I've been doing some more reading around Azure SQL and found the following document: https://msdn.microsoft.com/en-us/library/dn632678.aspx 

Are there any plans to implement idle connection resiliency, if not where would be a good place look at how to implement it, and where in the code base would it live?

**Comment by dimdin** [comment]
The driver cooperates with database/sql to reconnect by returning ErrBadConn when the connection is in a bad state. see #45 
This cannot help if the connection is lost when iterating a cursor or when you have started a transaction, because the connection state cannot be restored. Unfortunately the same limitations are stated in the connection resiliency document.

From http://golang.org/pkg/database/sql/driver/
"ErrBadConn should be returned by a driver to signal to the sql package that a driver.Conn is in a bad state (such as the server having earlier closed the connection) and the sql package should retry on a new connection."

**Comment by jamesRaybould** [comment]
Thanks for that, I've dug a bit more it seems that `CheckBadConn(err)` isn't been called on this error. The error happens at `sess.buf.BeginRead()` in `processResponse` this then bubbles up and is returned on `tokchan` that is then returned as an error for the user to deal with. That means it never comes close to the `CheckBadConn(err)` - I'm going to have a play with adding `CheckBadConn(err)` but what would be the preferred way of handling this?

**Comment by denisenkom** [comment]
This change actually broke some tests: TestShortTimeout and TestDefaultTimeout.
Would need to come up with some other solution.

**Comment by denisenkom** [comment]
I've set default for TCP keep alive to 30 seconds as described in spec: https://msdn.microsoft.com/en-us/library/dd341108.aspx

Please try again on latest version.
